export const COLAB_PENDING_NOMADE_STATE = 1; // nomade
export const COLAB_PENDING_COMPANY_STATE = 2; // nomade
export const COLAB_ACCEPTED_STATE = 3; // company
export const COLAB_MODIFICATION_IN_PROGRESS_STATE = 4; // influencer
export const COLAB_DONE_STATE = 5; // not used
export const COLAB_FINISHED_STATE = 6; // not used
export const COLAB_CANCELLED_STATE = 7; // company
export const COLAB_REJECTED_STATE = 8; // company - rejectedReason
export const COLAB_SENT_STATE = 9; // company
export const COLAB_RECEIVED_STATE = 10; // influencer
export const COLAB_INCIDENT_STATE = 11; // influencer
export const COLAB_PUBLISHED_STATE = 12; // influencer
