import {
  HeaderSection,
  SectionTypes,
} from "sections/shared/interfaces/interfaces";

export const monthPlansTableSections: HeaderSection[] = [
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 5,
    name: "Mínimo",
    property: "minimum",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Collabs",
    property: "colabs",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Fin plan",
    property: "end_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },

  {
    id: 8,
    name: "Progreso",
    property: "percentage",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Status",
    property: "status",
    sortTag: "company_status",
    pageName: SectionTypes.plans,
  },
];

export const trimestralPlansTableSections: HeaderSection[] = [
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 5,
    name: "Mínimo",
    property: "minimum",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Fecha inicio trimestre",
    property: "start_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Fecha fin trimestre",
    property: "end_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 8,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Collabs",
    property: "colabs",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 11,
    name: "Status",
    property: "status",
    sortTag: "company_status",
    pageName: SectionTypes.plans,
  },
];

export const planTableSections: HeaderSection[] = [
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 6,
    name: "Fecha inicio trimestre",
    property: "start_date",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 7,
    name: "Fecha fin trimestre",
    property: "end_date",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 8,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 9,
    name: "Collabs",
    property: "colabs",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 11,
    name: "Status",
    property: "status",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
];

export const companyPlanTableSections: HeaderSection[] = [
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Fecha inicio trimestre",
    property: "start_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Fecha fin trimestre",
    property: "end_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 8,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Collabs",
    property: "colabs",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 11,
    name: "Status",
    property: "status",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
];
