import {
  HeaderSection,
  SectionTypes,
} from "sections/shared/interfaces/interfaces";

export const monthPlansTableSections: HeaderSection[] = [
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 5,
    name: "Mínimo",
    property: "minimum",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Collabs",
    property: "colabs",
    sortTag: "colabs",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Inicio plan",
    property: "start_date",
    sortTag: "start_date",
    pageName: SectionTypes.plans,
  },
  {
    id: 8,
    name: "Fin plan",
    property: "end_date",
    sortTag: "end_date",
    pageName: SectionTypes.plans,
  },

  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "percentage",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Status",
    property: "status",
    sortTag: "company_status",
    pageName: SectionTypes.plans,
  },
];

export const trimestralPlansTableSections: HeaderSection[] = [
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 5,
    name: "Mínimo",
    property: "minimum",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Collabs",
    property: "colabs",
    sortTag: "colabs",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Fecha inicio trimestre",
    property: "start_date",
    sortTag: "start_date",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Fecha fin trimestre",
    property: "end_date",
    sortTag: "end_date",
    pageName: SectionTypes.plans,
  },
  {
    id: 8,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "remaining",
    pageName: SectionTypes.plans,
  },
  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "percentage",
    pageName: SectionTypes.plans,
  },
  {
    id: 11,
    name: "Status",
    property: "status",
    sortTag: "company_status",
    pageName: SectionTypes.plans,
  },
];

export const planTableSections: HeaderSection[] = [
  {
    id: 3,
    name: "Plan Contratado",
    property: "plan",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 2,
    name: "Periodicidad",
    property: "billing",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 4,
    name: "Mínimo de collabs",
    property: "minimum",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 5,
    name: "Máximo de collabs",
    property: "objective",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 6,
    name: "Fecha de alta",
    property: "created_at",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 7,
    name: "Fecha inicio plan",
    property: "start_date",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 8,
    name: "Fecha fin plan",
    property: "end_date",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 9,
    name: "Fecha de inicio de pago",
    property: "start_payment_date",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 10,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "",
    pageName: "offers",
  },
  {
    id: 11,
    name: "Collabs realizadas",
    property: "colabs",
    sortTag: "",
    pageName: "offers",
  },
];
export const userTableSections: HeaderSection[] = [
  {
    id: 8,
    name: "Imagen",
    property: "image",
    sortTag: "",
    pageName: "",
  },
  {
    id: 3,
    name: "Nombre comercial",
    property: "company",
    sortTag: "",
    pageName: "",
  },
  {
    id: 2,
    name: "Nombre",
    property: "company_name",
    sortTag: "",
    pageName: "",
  },

  {
    id: 12,
    name: "Teléfono",
    property: "phone",
    sortTag: "",
    pageName: "",
  },
  {
    id: 6,
    name: "Email",
    property: "email",
    sortTag: "",
    pageName: "",
  },
  {
    id: 7,
    name: "Web",
    property: "web",
    sortTag: "",
    pageName: "",
  },
  {
    id: 11,
    name: "Dirección",
    property: "address",
    sortTag: "",
    pageName: "",
  },
];
export const companyPlanTableSections: HeaderSection[] = [
  {
    id: 3,
    name: "Plan",
    property: "plan",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 4,
    name: "Objetivo",
    property: "objective",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 6,
    name: "Fecha inicio trimestre",
    property: "start_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 7,
    name: "Fecha fin trimestre",
    property: "end_date",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 8,
    name: "Tiempo restante",
    property: "remaining",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 9,
    name: "Collabs",
    property: "colabs",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 10,
    name: "Progreso",
    property: "percentage",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 15,
    name: "Período de prueba",
    property: "trial_period",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 12,
    name: "Comentario",
    property: "comments",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
  {
    id: 11,
    name: "Status",
    property: "status",
    sortTag: "",
    pageName: SectionTypes.plans,
  },
];
