import {
  HeaderSection,
  SectionTypes,
} from "../../shared/interfaces/interfaces";

export const companyTableHeaderSections: HeaderSection[] = [
  {
    id: 1,
    name: "Imágen",
    property: "image",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 2,
    name: "Cliente",
    property: "company_name",
    sortTag: "company_name",
    pageName: SectionTypes.customers,
  },
  {
    id: 3,
    name: "Web",
    property: "web",
    sortTag: "web",
    pageName: SectionTypes.customers,
  },
  {
    id: 4,
    name: "Teléfono",
    property: "phone",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 5,
    name: "Porcentaje",
    property: "percentage",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 6,
    name: "NIF",
    property: "nif",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 7,
    name: "Plan",
    property: "company_plan",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 7,
    name: "Tipo de pago",
    property: "company_billing",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 8,
    name: "Status",
    property: "status",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 9,
    name: "Comentarios",
    property: "company_comments",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 10,
    name: "Acciones",
    property: "actions",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
];

export const companyCollabsHeaderSections: HeaderSection[] = [
  {
    id: 1,
    name: "Influencer",
    property: "influencer_name",
    sortTag: "name",
    pageName: SectionTypes.customers,
  },
  {
    id: 3,
    name: "Día",
    property: "day",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 4,
    name: "Hora",
    property: "time",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 5,
    name: "Tipo",
    property: "type",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 6,
    name: "Estado",
    property: "history",
    sortTag: "",
    pageName: "influencer",
  },
  {
    id: 6,
    name: "Publicada",
    property: "published",
    sortTag: "",
    pageName: "influencer",
  },
  {
    id: 7,
    name: "Acciones",
    property: "actions",
    sortTag: "",
    pageName: "influencer",
  },
];
