import {
  HeaderSection,
  SectionTypes,
} from "../../shared/interfaces/interfaces";

export const companyTableHeaderSections: HeaderSection[] = [
  // {
  //   id: 1,
  //   name: "Logo",
  //   property: "image",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "company",
    pageName: SectionTypes.customers,
  },
  // {
  //   id: 3,
  //   name: "Web",
  //   property: "web",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 4,
  //   name: "Teléfono",
  //   property: "phone",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 5,
  //   name: "Progreso",
  //   property: "percentage",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 6,
  //   name: "NIF",
  //   property: "nif",
  //   sortTag: "nif",
  //   pageName: SectionTypes.customers,
  // },
  {
    id: 7,
    name: "Plan",
    property: "company_plan",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 8,
    name: "Tipo de pago",
    property: "company_billing",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 12,
    name: "Fecha de alta",
    property: "created_at",
    sortTag: "created_at",
    pageName: SectionTypes.customers,
  },
  {
    id: 9,
    name: "Status",
    property: "status",
    sortTag: "company_status",
    pageName: SectionTypes.customers,
  },
  {
    id: 10,
    name: "Comentarios",
    property: "company_comments",
    sortTag: "",
    pageName: SectionTypes.customers,
  },

  // {
  //   id: 10,
  //   name: "Acciones",
  //   property: "actions",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
];

export const companyFromUsersTableHeaderSections: HeaderSection[] = [
  // {
  //   id: 1,
  //   name: "Logo",
  //   property: "image",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  {
    id: 2,
    name: "Cliente",
    property: "company",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  // {
  //   id: 3,
  //   name: "Web",
  //   property: "web",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 4,
  //   name: "Teléfono",
  //   property: "phone",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 5,
  //   name: "Progreso",
  //   property: "percentage",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
  // {
  //   id: 6,
  //   name: "NIF",
  //   property: "nif",
  //   sortTag: "nif",
  //   pageName: SectionTypes.customers,
  // },
  {
    id: 7,
    name: "Plan",
    property: "company_plan",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 8,
    name: "Tipo de pago",
    property: "company_billing",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 12,
    name: "Fecha de alta",
    property: "created_at",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  {
    id: 9,
    name: "Status",
    property: "status",
    sortTag: "",
    pageName: SectionTypes.customers,
  },
  // {
  //   id: 10,
  //   name: "Acciones",
  //   property: "actions",
  //   sortTag: "",
  //   pageName: SectionTypes.customers,
  // },
];

export const companyCollabsHeaderSections: HeaderSection[] = [
  {
    id: 1,
    name: "Influencer",
    property: "influencer_name",
    sortTag: "influencer",
    pageName: SectionTypes.collabs,
  },
  {
    id: 3,
    name: "Día",
    property: "day",
    sortTag: "day",
    pageName: SectionTypes.collabs,
  },
  {
    id: 4,
    name: "Hora",
    property: "time",
    sortTag: "",
    pageName: SectionTypes.collabs,
  },
  {
    id: 5,
    name: "Tipo",
    property: "type",
    sortTag: "type",
    pageName: SectionTypes.collabs,
  },
  {
    id: 6,
    name: "Estado",
    property: "history",
    sortTag: "",
    pageName: SectionTypes.collabs,
  },
  {
    id: 7,
    name: "Publicada",
    property: "published",
    sortTag: "",
    pageName: SectionTypes.collabs,
  },
  {
    id: 8,
    name: "Acciones",
    property: "actions",
    sortTag: "",
    pageName: SectionTypes.collabs,
  },
];
