export const theme = {
  colors: {
    mainColor: "#335d53",
    secondaryColor: "#ECEDE6",
    tertiaryColor: "#FEDA94",
    inputsBorderColors: "#E7E6E6",
    light: "#fff",
    backgroundPages: "#F9F9F9",
    softGreen: "#30D59B",
    red: "#E02020",
    black: "#000",
    orange: "#F7B500",
    lightGrey: "#F6F6F6",
    darkBlue: "#002949",
    grey: "#CECECE",
    tagsBlue: "#2196F3",
    darkRed: "#AD6975",
    purple: "#7D26CD",
    softMainColor: "#d1d6c5",
    outerSpace: "#243c34",
    mineralGreen: "#335d53",
    seaMist: "#C8DCCD",
    antiqueWhite: "#F6EDD8",
    paleLime: "#CCF663",
    chineseWhite: "#E6E3DA",
  },
  fonts: {
    primaryFont: "Roboto",
  },
  fontsColors: {
    light: "#fff",
    dark: "#000",
    lightGrey: "#ABABB4",
    corporativeColor: "#335d53",
    error: "#E02020",
    darkBlue: "#125AA9",
    dashBoard: "#273241",
    success: "#30D59B",
    outerSpace: "#243c34",
    mineralGreen: "#335d53",
    seaMist: "#C8DCCD",
    antiqueWhite: "#F6EDD8",
    paleLime: "#CCF663",
    chineseWhite: "#E6E3DA",
  },
  borders: {
    lightGrey: "#E2E1E1",
    grey: "#ABABB4",
  },
  fontsSize: {
    __XS: "0.5rem",
    __S: "0.6rem",
    __SSM: "0.7rem",
    __SM: "14px",
    __SMM: "0.9rem",
    __M: "1rem",
    __ML: "1.2rem",
    __L: "1.5rem",
    __XXL: "2rem",
    __XXXL: "4rem",
    notFoundIcon: "15rem",
  },
  borderRadius: {
    inputs: "8px",
    badges: "5px",
    submitButton: "20px",
  },
  fontWeights: {
    mediumBold: "700",
  },
  heights: {
    inputs: "40px",
  },
  widths: {
    datasheetSmallInputs: "16.5rem",
    datasheetLargeInputs: "370px",
    datasheetExtraSmallIputs: "250px",
  },
};

export default theme;
