export const appPaths = {
  login: "/login",
  register: "/registro",
  orders: "/pedidos/page/:page",
  order: "/pedidos/:id",
  clients: "/clientes/page/:page",
  client: "/clientes/:id",
  clientOrders: "/clientes/pedidos/:id/page/:page",
  users: "/usuarios/page/:page",
  settings: "/configuración",
  account: "/mi-cuenta",
  place_order: "/realizar-pedido",
  recovery_password: "/recovery-password",
  reset_password: "/reset-password",
};
