export const appPaths = {
  login: "/login",
  register: "/registro",
  offers: "/ofertas/page/:page",
  clients: "/clientes/page/:page",
  client: "/cliente/:id",
  users: "/usuarios/page/:page",
  settings: "/configuración",
  account: "/mi-cuenta",
  place_order: "/realizar-pedido",
  recovery_password: "/recovery-password",
  reset_password: "/reset-password",
  collabs: "/collabs/page/:page",
  influencers: "/influencers/page/:page",
  influencer: "/influencer/:id",
  leads: "/leads/page/:page",
  leadsSubmit: "/client/register",
};
